export const patentsInfo = [
    {
       patentId: "US 7,643,821 B2",
        issued: "Jan 5, 2010",
        title: "Text Brochure and Media Systems and Method",
        claims: [
            "1) A brochure distribution device for use with an item to be sold, the device comprising: an advertisement of such item, the advertisement displaying thereon an access number, the access number operative to receive a first communication from a cellular communication device; a first database containing information concerning such item, such information selected from the group consisting of: text descriptions of such item, images of such item, video clips of such item, and combinations thereof; and a digital device comprising: a first operative connection from the access number; an active response system allowing immediate automatic response to connections from the access number, regardless of the message format, without prioritizing such communication based on a message format of the cellular communication device; and a response module able to receive, during the first communication to the access number, a designated cellular communication device number for responding to the first communication and, in response, to retrieve information from the database and send, as a second communication, an SMS-formatted brochure containing the information concerning such item to the designated cellular communication device, with the brochure formatted for receipt and display by the designated cellular communication device; wherein the SMS format of such brochure is capable of including links, text about the item, images of the item, and video clips of the item.",
            "2) The brochure distribution device of claim 1, wherein the access number further comprises: one member selected from the group consisting of: a telephone number, a short code, a computer network address and combinations thereof.",
            "3) The brochure distribution device of claim 1, wherein the first operative connection to the digital device from the access number further comprises: one member selected from the group consisting of: a cellular telecommunication network, a telecommunication gateway device, a telecommunication first tier provider, a telecommunication service aggregator, a hunter line, a listener line, a VOIP connection, a computer network, a telecommunication network, and also combinations thereof",
            "4) The brochure distribution device of claim 1, wherein the database of information concerning such item further comprises: one member selected from the group consisting of: property type, location, size, lot size of real estate, rooms within buildings, textual information concerning such item details of such item, short summaries of textual information and details of such item, images of the interior of such item, images of the exterior of such item, images of rear views of such item, legal details regarding such item, and combinations thereof.",
            "5) The brochure distribution device of claim 1, wherein the active response system of the digital device further comprises: one member selected from the group consisting of: an interactive voice response system, an interactive DTMF code response system, a text message parser, and combination thereof",
            "6) The brochure distribution device of claim 1, further comprising: a sales agent alert module, the alert module able to send a first alert message to a sales agent in response to receipt of a cellular communication device number during the first communication to the access number.",
            "7) The brochure distribution device of claim 6, wherein the first alert message further comprises: one member selected from the group consisting of: an SMS text message, a voice message, an e-mail, a facsimile message, a page, and combinations thereof.",
            "8) The brochure distribution device of claim 6, wherein the first alert message further comprises: the cellular communication device number.",
            "9) The brochure distribution device of claim 1, further comprising: a second database of information concerning such first communication to the access number",
            "10) The brochure distribution device of claim 1, wherein the first communication further comprises: an SMS message.",
            "11) The brochure distribution device of claim 1, wherein the response module of the digital device is further able, in response to the first communication, to send a second informational message.",
            "12) The brochure distribution device of claim 1, wherein the response module of the digital device is further able, in response to the first communication, to send an opt-in message",
            "13) A method of distributing information for an item, the method comprising the steps of: a) advertising such item displaying an access number operative to receive a first communication from a cellular communication device; b) actively seeking a first message made to such access number; c) upon receipt of the first message, routing, without prioritizing such message based on a message format of the cellular communication device, the first message to a digital device able to respond to the first message and recording the contact number of the cellular communication device; d) accessing a database of information concerning such item, such information selected from the group consisting of: text descriptions of such item, images of such item, video clips of such item, and combinations thereof; e) sending to such cellular communication device contact number an additional communication in the form of an SMS-formatted brochure containing the information concerning such item, the SMS format capable of including links, text about the item, images of the item, and video clips of the item and formatted for receipt and display by the designated cellular communication device",
            "14) The method of distributing information for an item of claim 13, wherein the database of information concerning such item further comprises: one member selected from the group consisting of: textual information concerning such item, details of such item, short summaries of textual information and details of such item, images of the interior of such item, images of the exterior of such item, images of rear views of such item, legal details regarding such item, advertisements, outcomes of events, and combinations thereo",
            "15) The method of distributing information for an item of claim 13, wherein the SMS format brochure further comprises: one member selected from the group consisting of: text, an image, and combinations thereof.",
            "16) The method of distributing information for an item of claim 13, further comprising: f) sending a first alert message to a sales agent in response to receipt of a cellular communication device number during the first communication to the access numb",
            "17) The method of distributing information for an item of claim 13, further comprising: g) collecting and maintaining information concerning the first communication."
        ],
        voice: {
            legalVoice: "SUMMARY OF THE INVENTION The present invention teaches a method and device for providing text brochures to interested parties using cellular communication devices such as cellular telephones, cellular enabled digital devices such as PDAs, computers, games, and the like. An access number which may be contacted by a cellular communication device.",
            businessVoice: "SUMMARY OF THE INVENTION The present invention teaches a method and device for providing ... TBD per AI Prompt: Provide a summary in common business tone ..",
            tenGradeVoice: "SUMMARY OF THE INVENTION The present invention teaches a method and device for providing ... TBD per AI Prompt: Provide a summary in 10th grade tone .."
        },
        fileDate: "Dec 17, 2005",
        inventor: "Kenneth P. O'Hanlon",
        abstract: "A method and device for providing brochures to interested parties using cellular communication devices such as cellular telephones, cellular enabled digital devices and the like. An access number which may be contacted by a cellular communication device is provided in an advertisement of an item, the access number being a short code, telephone number or the like. An active seeker device continuously receives messages sent to the access number, then a database of information is consulted and an informational message sent to the caller. The informational message may be an SMS text message, a photograph of the item, an opt-in message to receive further information, and combinations thereof. Items may include any object or estate commonly advertised for sale or lease, such as real estate, vehicles, consumer products and the like.",
        fieldOfInventor: "This invention relates generally to telecommunication devices, and specifically to the timely provision of text brochures and media brochures to potential buyers of an advertised product."
    },
    {
       patentId: "US 8,437,453 B2",
        issued: "May 7, 2013",
        title: "Dynamic Multiple Server IVR String",
        claims: [
            "1) A multiple server based interactive voice response (IVR) system for use by a caller with a first telephone not part of the system, the multiple server based IVR comprising: a general purpose computer programmed with a database of individual IVR strings, each individual IVR string associated with at least a self-identification telephone number and a first server connection to an external server, the multiple server based IVR system telephone accessible by each individual IVR string's self-identification telephone number; a first telephone number identifier operative to receive a first telephone number from a Dialed Number Identification Service (DNIS) when such first telephone calls the multiple server based IVR system at a first one of the self-identification telephone numbers; the first telephone number identifier further operative to compare the first telephone number received to each of the telephone numbers associated with the individual IVR strings. the first telephone number identifier operative to activate the first server connection to the external server of the individual IVR string associated with the self-identification telephone number matching the first telephone number: wherein the individual IVR strings each further comprise: a first greeting message associated with the individual IVR String; at least one set of at least two individual interactive responses available in the individual IVR string: a second post-response message associated with the individual IVR string and further associated with at least one of the individual interactive responses; and wherein the multiple server based IVR system further comprises: a string executor operative to play the messages of the individual IVR string when the individual IVR string is activated; wherein: the database further comprises at least one grouping of individual IVR strings; the first telephone number identifier further operative to identify a first group of individual IVR strings based on the first telephone number received; and the string executor further operative to play the messages of each individual IVR string of the first group",
            "2) The multiple server based interactive voice response (IVR) system of claim 1, wherein: the first telephone number identifier further comprises: a second identifier for receiving a second telephone number associated with the first telephone; and the database further comprises a second grouping of individual IVR strings, the second grouping of individual IVR strings each associated with the second telephone number",
            "3) The multiple server based interactive voice response (IVR) system of claim 1, further comprising: a second grouping of individual IVR strings wherein the second grouping of individual IVR strings are associated with an individual IVR string in the first grouping of individual IVR strings; and a selector associated with the string executor and operative to select from the second grouping of individual IVR strings when the first individual IVR string is selected.",
            "4) The multiple server based interactive voice response (IVR) system of claim 1, further comprising: a third grouping of individual IVR strings each associated with a first one of the individual IVR strings; and a string selector further associated with the string executor, the string selector operative to select an individual IVR string from the third grouping of individual IVR strings.",
            "5) The multiple server based interactive voice response (IVR) system of claim 1, wherein: each individual IVR string comprises a text interactive response."
        ],
        voice: {
            legalVoice: "SUMMARY OF THE INVENTION The present invention teaches a method and device for providing ... TBD per AI Prompt: Provide a summary in common business tone ..",
            businessVoice: "SUMMARY OF THE INVENTION The present invention teaches a method and device for providing ... TBD per AI Prompt: Provide a summary in common business tone ..",
            tenGradeVoice: "SUMMARY OF THE INVENTION The present invention teaches a method and device for providing ... TBD per AI Prompt: Provide a summary in 10th grade tone .."
        },
        fileDate: "Oct 7, 2007",
        inventor: "John Smith",
        abstract: "The present invention relates generally to multiple server-based interactive voice response (IVR) systems. Specifically, the invention discloses a method and apparatus for dynamically creating, managing, and executing IVR strings across multiple servers, based on a set of predefined conditions and identifiers such as dialed numbers. The IVR strings can include various interactive responses, greetings, and messages, which are selected based on the caller's input and system configuration.",
        fieldOfInventor: "This invention relates generally to interactive voice response (IVR) systems, and more specifically to the use of multiple server systems to manage and dynamically select individual IVR strings."
    },
    
    {
       patentId: "US 8,774,371 B1",
        issued: "May 7, 2013",
        title: "Dynamic Multiple Server Interactive Response System",
        claims: [
            "1) A multiple server based interactive response system for use by a customer with a first communication device not part of the system, the multiple server based response system comprising: a general purpose computer programmed with a database of individual message strings, each individual message string associated with a plurality of self-identification items selected from telephone numbers, text message codes, email addresses, web page URLs, images, video recordings, QR codes, ShotCodes, MobiTags, 2-dimensional bar codes, 3-dimensional bar codes, and combinations thereof, said computer having a first server connection to an external server, the multiple server based message system communication device accessible by each individual message string's self-identification items; a first communication device identifier operative to receive first communication device identification selected from telephone numbers, email addresses, and combinations thereof, when a communication is received from the first communication device by the multiple server based response system at via first one of the self-identification items; wherein: the first communication device identifier is further operative to compare the first communication device identification received to each of the self-identification items associated with the individual message strings and to activate the first server connection to the external server of the individual message string associated with the self-identification item received from the first communication device.",
            "2) The multiple server based interactive response system of claim 1, wherein the individual message strings each further comprise: a first greeting message associated with the individual message string; at least one set of at least two individual interactive responses available in the individual message string; and a second post-response message associated with the individual message string and further associated with at least one of the individual interactive responses; and the multiple server based message system further comprises a string executor operative to play the messages of the individual message string when the individual message string is activated.",
            "3) The multiple server based interactive response system of claim 2, wherein the individual message string messages further comprise files of a format selected from the group consisting of audio file formats, email formats, text message formats, image formats, video formats, other formats now known, and combinations thereof.",
            "4) The multiple server based interactive response system of claim 2, wherein the string executor further is a module of the multiple server based interactive response system.",
            "5) The multiple server based interactive response system of claim 2, wherein the string executor further is based on the external server of the individual message string.",
            "6) The multiple server based interactive response system of claim 1, wherein the first server connection is a computer network.",
            "7) The multiple server based interactive response system of claim 6, wherein the computer network is the Internet.",
            "8) The multiple server based interactive response system of claim 2, further comprising: at least one association module allowing creation and change of the association of the second post-response message with at least one of the individual interactive responses.",
            "9) The multiple server based interactive response system of claim 2, wherein: the database further comprises at least two individual message strings both associated with the same self-identification item; the database further comprises a second feature associated with the individual message string, said second feature selected from telephone numbers, email addresses, and combinations thereof; the system further comprises a second communication device identifier operative to receive therein a second device identification selected from telephone numbers, email addresses, and combinations thereof when the first communication device contacts the multiple server based message system; and wherein the second device identifier is further operative to compare the second feature to each of the second features associated with the individual message strings; and wherein the system is further operative to activate the first server connection to the external server of the individual message string associated with the second device identification as well as the self-identification item matching the first number.",
            "10) A multiple interactive response system controllable by a non-technical individual message system owner, the response system comprising: a database of individual message strings, each individual message string in turn comprising: an identification item selected from telephone numbers, text message codes, email addresses, web page URLs, images, video recordings, QR codes, ShotCodes, MobiTags, 2-dimensional bar codes, 3-dimensional bar codes, and combinations thereof, associated with the individual message string; a first greeting message associated with the individual message string; at least one set of at least two individual interactive responses available in the individual message string; and a second post-response message associated with the individual message string and further associated with at least one of the individual interactive responses; wherein: the database of individual message strings further allows access to each of the identification items associated with the individual message strings; a first communication device identifier operative to receive a first communication device identifier selected from telephone numbers, email addresses, and combinations thereof, when a first communication device contacts the multiple message system via the first self-identification item; the first communication device identifier further operative to compare the first identification item to each of the identification items associated with the individual message strings; an initiator operative to attach an individual message string associated with an identification item matching the first identification item; a connection operative to connect the first communication device to the individual message string associated with the identification item matching the first identification item; at least one input module allowing such non-technical individual message system owner to input at least one.",
            "11) The multiple interactive response system controllable by a non-technical individual message system owner of claim 10, further comprising: at least one association module allowing such non-technical individual message system owner to create and change such association of the second post-response message with at least one of the individual interactive responses.",
            "12) The multiple interactive response system controllable by a non-technical individual message system owner of claim 10, wherein: the database further comprises at least two individual message strings both associated with the same first identification item; the database further comprises a second identification item associated with the individual message string; and further comprising a second identification item identifier operative to receive therein a second identification item selected from telephone numbers, email addresses, and combinations thereof, when the first communication device contacts the multiple message system; and wherein the second communication device identifier is further operative to compare the second identification item to each of the identification items associated with the individual message strings; and wherein the initiator is further operative to attach an individual message string associated with the second identification item; and wherein the connection is further operative to connect the first communication device to the individual message string associated with the identification item matching the second identification item received from a communication device identifier as well as the telephone number matching the first communication device identification received from the communication device identifier.",
            "13) The multiple interactive response system controllable by a non-technical individual system owner of claim 10, wherein: the database further comprises a product ID number associated with the individual message string; the system further comprises a product ID number identifier operative to query for and receive a product ID number from the first communication device; the product ID number identifier is further operative to compare the product ID number to each of the product ID numbers associated with the individual message strings; and wherein the initiator is further operative to attach an individual message string associated with the product ID number; and the connection is further operative to connect the first communication device to the individual message string associated with the matching product ID number."
        ],
        voice: {
            legalVoice: "SUMMARY OF THE INVENTION The present invention teaches a multiple server based interactive voice response (IVR) system in which an index computer receives calls initially placed. Individual IVR strings in a database of such strings ...",
            businessVoice: "SUMMARY OF THE INVENTION The present invention teaches a multiple server based interactive voice response (IVR) system in which an index computer receives ... TBD per AI Prompt: Provide a summary in common business tone ...",
            tenGradeVoice: "SUMMARY OF THE INVENTION The present invention teaches a multiple server based interactive voice response (IVR) system in which an index computer receives ... TBD per AI Prompt: Provide a summary in 10th grade tone ..."
        },
        abstract: "A multiple server based interactive voice response (IVR) system in which individual IVR strings on an index computer are associated with connections to external servers, the IVR system index computer accessible by each individual IVR string's self-identification telephone number either from Dialed Number Identification Service (DNIS) information, Automatic Number Identification (ANI) service information, item ID information provided by a caller, or a combination thereof. When a call is received by the IVR system index computer, it uses DNIS, ANI, and/or item ID information to route the call to string information (outgoing messages, menu options, etc.) which might be located on the index computer or on a client computer. In embodiments, the client business might be able to easily access the information associating options to messages and the message files themselves and change their IVR string without technical support.",
        fieldOfInventor: "This invention relates generally to telephone response system devices, and specifically to interactive voice response devices.",
        inventor: "Kenneth P. O'Hanlon",
        fileDate: "May 6, 2013"
    },
    {
       patentId: "US 8,817,959 B1",
        issued: "Aug 26, 2014",
        title: "System for Handling Messages and Distributing Information",
        claims: [
            "1) A system for handling messages and distributing information, comprising: means for processing information; means for receiving incoming messages from customer telecommunication devices, said incoming messages selected from telephone calls, text messages, email messages, code messages, images, video, and combinations thereof, and for sending outgoing messages selected from text messages and email messages, said means for receiving incoming and sending outgoing messages in communication with said means for processing information; means for transmitting incoming subscriber information from a subscriber communication device to said means for processing and for sending lead reports from said means for processing to said subscriber device; a subscriber database with information relating to at least one subscriber, said subscriber database accessible by said means for processing information; an item database with web page URLs provided by the at least one subscriber containing information about at least one item offered by the at least one subscriber to the customers, said item database accessible by said means for processing information; and a customer database containing identifying information about the customers, said customer database accessible by said means for processing information; wherein said system is capable of performing, during an interaction with a customer, operations selected from: receiving a request from a customer telecommunication device for additional information; sending messages to the customer telecommunications device to provide links to URLs containing information from said item database combined with identifying information about the particular customer device to the customer devices, said identifying information selected from the telecommunications device model, the telecommunications device telephone number, the telecommunications device network address, and combinations thereof; responding to a request from a customer for information by combining at least one URL from said item database with identifying information about the customer to form a new URL and sending an outgoing message with a link to the new URL to the customer, said outgoing message formatted for the telecommunication device model; tracking said identifying information about the customer device for each request for information received from the customer, said identifying information selected from the telecommunications device model, the telecommunications device telephone number, the telecommunications device network address, and combinations thereof; and sending reports to the subscriber whose information was requested, said reports including the date and time said subscriber information was requested, identifying information about the contact, and identifying information about the items associated with the URLs the customer requested and for which the links were opened on the customer telecommunications device.",
            "2) The system of claim 1, further comprising a message handler for receiving incoming messages from customers and transmitting outgoing messages to customers.",
            "3) The system of claim 2 further comprising a subscriber programmable IVR in communication with said message handler.",
            "4) The system of claim 1, wherein the content of said item database is subscriber-controlled.",
            "5) The system of claim 1, wherein said messages sent to the customer telecommunications device are selected from text messages and email messages.",
            "6) The system of claim 1, wherein said system comprises an internet wagering system.",
            "7) The system of claim 1, wherein said system comprises an emergency response system, and each said at least one subscriber is an emergency responder.",
            "8) The system of claim 1, wherein: said system further comprises a contact database containing identifying information about contact telecommunication devices to which information may be sent independently of communications with customer devices, said contact database accessible by said means for processing information; and said system is capable of performing, during an interaction with a contact, operations selected from: initiating a contact with a contact telecommunications device using contact identifying information retrieved from said contact database; receiving a request from the contact telecommunications device for additional information; sending messages including links to URLs containing information from said database combined with identifying information about the particular contact device to the contact devices, said identifying information selected from the telecommunications device model, the telecommunications device telephone number, the telecommunications device network address, and combinations thereof; responding to a request from a contact telecommunications device for information by combining at least one URL from said item database with identifying information about the contact to form a new URL and sending an outgoing message with a link to the new URL to the contact, said outgoing message formatted for the telecommunications device model; tracking the identifying information about the contact device for each request for information received from the contact, said identifying information selected from the telecommunications device model, the telecommunications device telephone number, the telecommunications device network address, and combinations thereof; sending reports to the subscriber whose information was requested, said reports including the date and time said subscriber information was requested, identifying information about the contact, and said items associated with the URLs the contact requested and for which the links were opened on the contact telecommunications device; and combinations thereof.",
            "9) The system of claim 8, wherein said messages sent to the customer telecommunications device are selected from text messages and email messages.",
            "10) The system of claim 8, wherein: said system comprises an emergency response system; each said at least one subscriber is an emergency responder; each customer is a person who initiates an interaction with said system via a text or email message; said system is operative to initiate an interaction with at least one contact telecommunications device with a message selected from text messages, email messages, and combinations thereof; and said system is operative to receive notifications from each contact telecommunications device, said notification indicating the date and time the outgoing message was viewed and identifying information about the contact telecommunications device.",
            "11) The system of claim 8, wherein said system is further operative to perform functions selected from: receiving, from a customer, contact identifying information about a plurality of contacts from a customer, said contact identifying information selected from contact names, contact email addresses, and contact telephone numbers; storing said contact identifying information in said contact database; retrieving said contact identifying information from said contact database, said contact information selected by a subscriber; and combinations thereof.",
            "12) The system of claim 1, wherein: incoming and outgoing text messages are handled with the same priority as telephone calls; incoming and outgoing text messages are unlimited in length; and incoming and outgoing text messages include SMS formatted information selected from text, links to URLs, images, video, and combinations thereof.",
            "13) The system of claim 1, wherein: incoming and outgoing text messages are handled with the same priority as telephone calls; incoming and outgoing text messages are unlimited in length; and incoming and outgoing text messages include SMS formatted information selected from text, links to URLs, images, video, and combinations thereof. The system of claim 6, further comprising at least one feature selected from: customer opt-in features for receiving additional information; customer opt-out features for receiving additional information; customer opt-in features for opting into geolocation by said system; customer opt-out features for opting out of geolocation by said system; contact opt-in features for receiving additional information; contact opt-out features for receiving additional information; contact opt-in features for opting into geolocation by said system; contact opt-out features for opting out of geolocation by said system.",
            "14) The system of claim 1, wherein said customer device contact information incorporated into said new URL is encrypted as a hash digest.",
            "15) The system of claim 1, wherein said means for processing information comprises a server.",
            "16) The system of claim 1, wherein said system is operative to allow each subscriber to change subscriber landing and flyer page URLs previously provided and stored in said item database and key words and tags for search engine optimization.",
            "17) A method for handling messages and distributing information, comprising the steps of: a. receiving subscriber information including identifying information about each subscriber, and a plurality of URLs including at least one flyer page URL and at least one landing page URL with a link to at least one of said flyer page URLs, for which URLs the customer wants links disseminated; storing said subscriber identifying information in a subscriber database and storing said landing and flyer page URLs in an item database; b. receiving an initial request from a customer telecommunications device for a subscriber landing page URL in said item database, said request being in response to an advertisement and having a format selected from telephone calls, text messages, email messages, codes, images, and video; c. collecting identifying information about said customer telecommunications device, said information selected from email addresses, telephone numbers, and combinations thereof and retrieved from a location selected from said customer device, a customer database, and combinations thereof; d. retrieving said landing page URL, combining said landing page URL with said customer device identifying information to form a new landing page URL with said customer device identifying information included in each flyer page link on said landing page; e. sending an outgoing message to the customer device, said message including a link to said new landing page URL; f. receiving a request from said customer device to display a flyer page URL corresponding to a link on said landing page; g. retrieving said customer-requested flyer page URL from said item database, combining said customer-requested URL with said customer device identifying information to form a new flyer page URL, said new flyer page URL including at least one link to an additional flyer page URL; h. sending an outgoing message to the customer device, said message including said new URL; i. reporting the date and time when said incoming request was received to a subscriber device; and j. storing said reported information in said customer data base.",
            "18) The method of claim 17, wherein steps f through are repeated.",
            "19) The method of claim 17, further comprising the steps of: forming a session containing information about said customer device; recording in said session the date and time of each customer request for a subscriber landing page and each customer request for a subscriber flyer page, said identifying information about the customer device; and which subscriber landing and flyer pages were requested; saving said session in said customer database; and retrieving said session from said customer database.",
            "20) The method of claim 17, wherein said customer device identifying information is encrypted in each message sent to said customer device.",
            "21) A method for handling messages and distributing information, comprising the steps of: a. receiving subscriber information including identifying information about each subscriber, and a plurality of URLs including at least one flyer page URL and at least one landing page URL with a link to at least one of said flyer page URLs, for which URLs the subscriber wants links disseminated; storing said subscriber identifying information in a subscriber database and storing said landing and flyer page URLs in an item database; b. receiving identifying information about at least one contact telecommunications device, said contact identifying information including data selected from the contacts name, the device telephone number, the telephone network address, and combinations thereof, and storing said contact information in a contact database; c. receiving subscriber information including a selection of at least one of said landing page URLs in said item database, at least one of said flyer page URLs in said item database, and at least one contact selected from said contact database; d. sending an outgoing message to each of said selected contacts, each of said outgoing messages including a link to at least one of said landing page URLs, with each outgoing message having a format selected from text messages and email messages; e. receiving a response from a contact device requesting one of said landing page URLs; f. retrieving said landing page URL, combining said landing page URL with said contact device identifying information to form a new landing page URL with said contact device identifying information included in each flyer page link on said landing page; g. sending an outgoing message to the contact device, said message including a link to said new landing page URL; h. receiving a request from said contact device to display a flyer page URL; i. retrieving said contact-requested flyer page URL from said item database, combining said contact-requested URL with said contact device identifying information to form a new flyer page URL, said new flyer page URL including at least one link to an additional flyer page URL: j. Sending an outgoing message to the contact device, said message including said new URL; k. reporting the date and time when said incoming request was received to a subscriber device; and l. storing said reported information in said contact database.",
            "22) The method of claim 21, wherein steps h through 1 are repeated.",
            "23) The method of claim 21, further comprising the steps of: forming a session containing information about the contact device; recording in said session the date and time of each contact request for a subscriber landing page and each contact request for a subscriber flyer page, said identifying information about the contact device, and which subscriber landing and flyer pages were requested; saving said session in said contact database; and retrieving said session from said contact database.",
            "24) The method of claim 21, wherein said contact device identifying information is encrypted in each message sent to said contact device."
        ],
        voice: {
            legalVoice: "SUMMARY OF THE INVENTION The present invention teaches a method and device for providing text brochures to interested parties using cellular communication devices such as cellular telephones, cellular enabled digital devices such as PDAs, computers, games, and the like. An access number which may be contacted by a cellular communication device.",
            businessVoice: "SUMMARY OF THE INVENTION The present invention teaches a method and device for providing ... TBD per AI Prompt: Provide a summary in common business tone ..",
            tenGradeVoice: "SUMMARY OF THE INVENTION The present invention teaches a method and device for providing ... TBD per AI Prompt: Provide a summary in 10th grade tone .."
        },
        abstract: "System for handling messages and distributing information between subscribers and their customers and contacts. Each system Subscriber can generate customized landing and flyer web pages called flyer pages for each of the subscriber's products, services, and/or listings. Landing and flyer pages can contain multiple links to other flyer pages. When a Subscriber's customer or contact views a landing or flyer page and clicks on a link presented on that page, the system provides Subscribers information to a customer or contact immediately after the information is requested. The system can also make a lead, including a record of that event, and present the record to the subscriber who owns the landing or flyer page, allowing a Subscriber to view a report with a history of who has viewed which page for all leads generated for their pages. Leads are tracked through a process that includes steps of lead generation and lead propagation. Embodiments of the system include a system for tracking sales leads, an internet-based wagering system, and an emergency response system.",
        fieldOfInventor: "The present invention relates generally to a system for handling messages and distributing information that interacts with a digital telephonic device, and more particularly to a system for providing leads based on requests for information.",
        fileDate: "May 26, 2013",
        inventor: "Kenneth P. O'Hanlon"
    },
    {
       patentId: "US 9,038,887 B1",
        issued: "Mar 2, 2001",
        title: "System for Responding to QR Codes, Shotcodes, Mobitags, 2-Dimensional Bar Codes, and Images",
        claims: [
            "1) A system for responding to codes, the codes selected from Quick Response (QR) codes, shotcodes, mobitags, 2-dimensional bar codes, 3-dimensional bar codes, and images; send messages and to distribute information, said system operative to perform functions selected from: a) responding to codes Scanned by a reader, the reader having multiple communication ports including a telephone port with an associated telephone number, wherein said system comprises: a code associated with an item and recognizable by the reader; a Universal Resource Locator (URL) associated with a provider of said code and item, wherein said URL is accessible via said code; a multifunctional link that is operative to interact with said URL and to open the telephone port and at least one additional communication port of the reader when said link is accessed by the reader; a platform that is operative to receive information from said communication ports, said information including the telephone number of the reader, said platform also being operative to transmit information to the reader; and a lead router that receives communications from said platform and routes said information to said provider, wherein said information includes the associated telephone number; b) associating telephone numbers with text transmissions, wherein said system comprises: means for receiving data simultaneously from a telephone port having an associated telephone number and a text port, both ports in a telecommunications device; means for transmitting data including said telephone number to said text port; and means for transmitting additional data including said telephone number to a tracking system; and c) communicating with an information sending/receiving device, said device having a camera and a unique user identification, wherein: said system comprises: means for receiving a message from the sending device and opening an URL, means for finding the unique user identification of the sending device, means for determining from the user identification the make and model of the sending device; and means for formatting messages for receipt by the sending device; and communicating with said information sending/receiving device comprises the steps of: opening a telephone port of the sending/receiving device to obtain a telephone number associated with the device; and tying the telephone number to the unique user identification; and d) combinations thereof.",
            "2) The system of claim 1, comprising functions (a), wherein said information transmitted to the reader comprises links to URLs that include the associated telephone number.",
            "3) The system of claim 1, comprising functions (a), further comprising: a code generator operative to create said code: a code scanner having a unique identifier associated with the telephone number of the reader; and means for using said identifier to associate the telephone number with one or more features selected from links to URLs, text messages, Wireless Application Protocol (WAP) pages of the reader, and WAP locating functions of the reader.",
            "4) The system of claim 3, wherein said scanner is downloadable to the reader and adapted for use with the particular type of reader for recognizing said code.",
            "5) The system of claim 3, wherein said scanner is operative to retrieve information from images, said images selected from Quick Response (QR) codes, ShotCodes, MobiTags, 2-dimensional bar codes, 3-dimensional bar codes, photographic images, and video recordings.",
            "6) The system of claim 1, comprising functions (a), comprising a plurality of lead routers for routing said information to a plurality of providers.",
            "7) The system of claim 1, comprising functions (b), wherein said means for receiving data comprises a multifunctional link operative to keep said telephone port and said text port open simultaneously.",
            "8) The system of claim 1, comprising functions (b), wherein said additional data comprises leads and said tracking system is a lead routing system.",
            "9) The system of claim 1, comprising functions (b), wherein said system further comprises a database of information for transmittal to said text port.",
            "10) The system of claim 1, comprising functions (a), further comprising: a code generator operative to create said code: a code scanner having a unique identifier associated with the telephone number of the reader; and means for using said identifier to associate the telephone number with one or more features selected from links to URLs, text messages, Wireless Application Protocol (WAP) pages of the reader, and WAP locating functions of the reader.",
            "11) The method of claim 10, wherein said requested information in step g is a text message.",
            "12) The method of claim 10, wherein said requested information in step g comprises at least one link to a Supplemental URL comprising the phone number of the reader, and said method further comprises the steps of: i. receiving a user selection from the reader of one of said links to a supplemental URL; and j. routing said phone number and information about the selection to a lead retrieval system.",
            "13) The method of claim 12, wherein said lead router is different from said lead retrieval system of step j.",
            "14) A system for handling a code associated with an item, said code including instructions for providing information about the item, said system comprising: means for receiving an image of said code from a data port of a sending/receiving device; means for scanning said image to obtain said instructions; and means for carrying out said instructions, said means comprising a multifunctional link operative to maintain multiple ports of the sending/receiving device open; wherein said instructions include the steps of: opening a telephone port of said sending/receiving device, said telephone port having an associated telephone number; associating the telephone number with information to be sent to the data port; and transmitting said information to the sending/receiving device.",
            "15) The system of claim 14, wherein said means for scanning operates in the sending/receiving device.",
            "16) The system of claim 15, wherein: said means for scanning is a downloadable software application specific for use with the sending/receiving device: said application is associated with a unique identifier; and said means for carrying out comprises means for associating said unique identifier with the telephone number and means for using said unique identifier and the telephone number for formatting said information for the sending/receiving device.",
            "17) The system of claim 14, wherein said code is selected from Quick Response (QR) codes, ShotCodes, MobiTags, 2-dimensional bar codes, 3-dimensional bar codes, images, video, and combinations thereof.",
            "18) The system of claim 14, wherein said means for carrying out instructions comprises a platform operative to associate the telephone number with said data information.",
            "19) The system of claim 14, wherein said means for carrying out instructions is operative to send messages including the telephone number to a message router."
        ],
        voice: {
            legalVoice: "SUMMARY OF THE INVENTION To achieve the foregoing and other objects and in accordance with the purpose of the present invention broadly described herein, one embodiment of this invention comprises a system for responding to codes Scanned by a reader. The reader has multiple communication ports, including a telephone port ..",
            businessVoice: "SUMMARY OF THE INVENTION To achieve the foregoing and other objects and in accordance with ... TBD per AI Prompt: Provide a summary in common business tone ..",
            tenGradeVoice: "SUMMARY OF THE INVENTION To achieve the foregoing and other objects and in accordance with ... TBD per AI Prompt: Provide a summary in 10th grade tone .."
        },
        abstract: "System, including a code scanner, for using multi-function codes, such as multi-function QR codes, MobiTags, Shot Codes, 2-dimensional bar codes, 3-dimensional bar codes, or images to open multiple ports of a telephone device. One of the ports is a text port, enabling the system to obtain the telephone number of a device that reads a code associated with an item and then generate a lead for follow-up by an agent. The lead is sent to the agent via a text or email message. The system may also pass the lead to other agents if the first agent doesn't respond, and it may also send additional information to the telephone device. The system may include a database of item-associated information and the capability of accessing the item-associated information for inclusion in outgoing messages to the agents and/or the telephone device.",
        inventor: "Kenneth P. O'Hanlon",
        fieldOfInventor: "The present invention relates generally to systems for providing and responding to codes that are readable with a digital telephonic device, and more particularly to a system for generating and responding to QR codes, ShotCodes, MobiTags, 2-dimensional bar codes, 3-dimensional bar codes, images, and video.",
        fileDate: "Jun 28, 2012"
    }


];